# Upstream changes from _extends are only recognized when modifications are made to this file in the default branch.
_extends: .github
repository:
  name: terraform-aws-service-quotas
  description: Terraform module to manage AWS Service Quotas
  homepage: https://cloudposse.com/accelerate
  topics: ""
